### ISSUE TITLE
Bighugh vs. bighuge

### ISSUE THREAD

**Issue by OAGr** [matryer/goblueprints#10]
In chapter 4, words.bighugelabs.com is referenced, which does exist, but bighughlabs.com also is referenced, which does not exist. Then in the codebase for the thesaurus package, there are several references to ```BigHugh```.  Am I missing something here?

**Comment by matryer** [comment]
It should be: https://words.bighugelabs.com

**Comment by matryer** [comment]
I've added a note to the main README. Thanks.
