### ISSUE TITLE
Question regarding to chat example: why do we even need the default case?

### ISSUE THREAD

**Issue by ghost** [matryer/goblueprints#16]
Hi Mr Ryer, I am studying your book and have a question regarding to the first example in the book. 

On page 19, in the func (r *room) run() function, you put a default case in the for...select structure handling message forwarding. Code snippt: 
```
func (r *room) run() {
	for {
		select {
		case client := <-r.join:
			// joining
			r.clients[client] = true
			r.tracer.Trace("New client joined")
		case client := <-r.leave:
			// leaving
			delete(r.clients, client)
			close(client.send)
			r.tracer.Trace("Client left")
		case msg := <-r.forward:
			r.tracer.Trace("Message received: ", string(msg))
			// forward message to all clients
			for client := range r.clients {
				select {
				case client.send <- msg:
					// send the message
					r.tracer.Trace(" -- sent to client")
				default:
					// failed to send
					delete(r.clients, client)
					close(client.send)
					r.tracer.Trace(" -- failed to send, cleaned up client")
				}
			}
		}
	}
}
```

My question is, since you've handled the leave case gracefully, why do you even need the default block?

You explain in the text on page 20:

> If we receive a message on the leave channel, we simply delete the client type (should be 'pointer'?) from the map, and close its send channel. Closing a channel has special significance in Go, which becomes clear when we look at our final select case.

> ... If the send channel is closed, then we know the client is not receiving any more messages, and this is where our second select clause (specifically the default case) takes the action of removing the client from the room and tidying things up.

It seems the only situation the "default" case would be reached is that the leave case has closed the client.send channel in prior to the forward case. But in the leave case, you have deleted the client from the clients map before close its send channel, so by no means the for...range loop in the forward case could touch the already-deleted client, and the default case should be never reached. The synchronized nature of select structure, as you mentioned earlier in the text, guarantees this behavior.

Have I missed anything? Or my understanding to the concurrency of Go is flawed? I am new to Go and would like to have your advise.

Thank you!

**Comment by matryer** [comment]
Thanks for your question.

I think it’s a property of how the solution evolved, and you might be right that it’s no longer needed. Originally, the joining and leaving was done in the room ServeHTTP and the default case was triggered when the channel was closed externally. But as you say, the only this that will close the channel is the leave case.

It does, however, allow the client to remove itself ‘manually’, just by closing its send channel - but that isn’t what happens in our code.

I’d be interested in what other people thought too?

I think you have a great understanding of channels :)

Mat

**Comment by slickmonk** [comment]
Thank you for your quick response. Your book is inspiring and your solutions are superior to what I saw in other online materials, I enjoy reading it very much. Thanks!

**Comment by matryer** [comment]
Thanks very much. Have a great day.

Mat
