### ISSUE TITLE
chat.go unable to comple: Undefined room

### ISSUE THREAD

**Issue by anthonyjp87** [matryer/goblueprints#19]
HI Matryer, 

I'm having a trouble executing the source code from Blueprints Chapter 1. On execution I get the error, /client.go:17 "Undefined: room". I'm finding this error with both my copy of the code written along with chapter 1 in the book, as well as your source code here in Github. I've created the room.go in the same folder and added the appropriate code, but I'm  uncertain why the client.go isn't registering and executing it. Do you also see this error when executing the source code?

-Thanks, anthonyjp87

**Comment by matryer** [comment]
How are you running the code?

If you use `go run` then it won’t compile everything into one binary. Be sure to use `go build -o appname` to have it bundle everything together, then you can run it with `./appname`.

Let me know if that wasn’t the issue.

**Comment by anthonyjp87** [comment]
Many thanks--that was my problem. I'm enjoying this book a lot. -cheers

**Comment by matryer** [comment]
Apologies if that wasn’t clear in the book.

Great to hear :) You’re going to love Go.

Please close the issue.
