### ISSUE TITLE
Ch. 6: Wrong tag string in `poll` struct.

### ISSUE THREAD

**Issue by ReSTARTR** [matryer/goblueprints#20]
HI Mat,

I found a wrong tag string in "Handling endpoints" section on ch. 6.

```go
// api/polls.go
type poll struct {
    Title string `json":"title""`
}
```

The double quote before `:` in this tag doesn't seem to be needed.

```go
// api/polls.go
type poll struct {
    Title string `json:"title""`
}
```

_It's collect in this repository code.(https://github.com/matryer/goblueprints/blob/f957fa0c4471ce74c877f0c6fb77d1e4eb78dd8e/chapter6/api/polls.go#L12)_

**Comment by matryer** [comment]
Thanks.
