### ISSUE TITLE
Why use eval to convert JSON into an object in Chapter 2?

### ISSUE THREAD

**Issue by F21** [matryer/goblueprints#22]
`eval` is used to parse the JSON in chapter 2: https://github.com/matryer/goblueprints/blob/master/chapter2/chat/templates/chat.html#L51

Wouldn't `JSON.parse(e.data)` be a better choice?

**Comment by matryer** [comment]
Yes it would :)

**Comment by F21** [comment]
Can you merge PR #14? :smile:
