### ISSUE TITLE
chapter4/thesaurus/thesaurus.go - interface not used?

### ISSUE THREAD

**Issue by davidhtims** [matryer/goblueprints#27]
The interface, Thesaurus, we create in Chapter 4 does not seem to be used in the rest of the code?

If I haven't missed something how would the code change if we did require this interface?

I think I need a little more explanation here please.

**Comment by matryer** [comment]
It's more the idea of describing an interface, which we then provide the first (or default) implementation of. But it would let others (outside the code) contribute their own implementations, and they wouldn't be forced to use ours.

**Comment by davidhtims** [comment]
Would it be clearer if we used a var statement first, in synonyms/main.go?

`var thesaurus thesaurus.Thesaurus`

Then we actually use the interface in this example code?

**Comment by davidhtims** [comment]
Thanks Mat,that is pretty much what yous said in the book. Are you saying that the interface would never get used in the code and that it is just a guide to future users?

**Comment by matryer** [comment]
Yeah, and you might well decide not to do this. Instead, you could provide a concrete type and let other users write an interface that fits if they need it. As an extra exercise, you could try writing a test implementation that doesn't use a real web service?
