### ISSUE TITLE
Running list of revisions from 1st edition

### ISSUE THREAD

**Issue by josephreynolds** [matryer/goblueprints#30]
Hi Mat,

It's great you're maintaining and updating this repository. What's the best way for a reader of the 1st edition to follow and track the revisions? Is it the '2nd edition' label?  

Thanks

**Comment by matryer** [comment]
The list in the README is the best way to see the main points. Then, if you're interested in changes, check out the History for each file (from master), then you'll see what changes have been made. Usually they're just code-style improvements. Bug fixes and other breaking changes are listed in the README.
