### ISSUE TITLE
In chapter 2, callback URL of "provider".New() shouldn't fix the port.

### ISSUE THREAD

**Issue by entyo** [matryer/goblueprints#31]
In chapter 2, PROVIDER.New() (github, facebook, etc) has a parameter which specifies the callback URL. (https://github.com/matryer/goblueprints/blob/master/chapter2/chat/main.go#L51)

```go:main.go
    gomniauth.WithProviders(
		github.New("3d1e6ba69036e0624b61", "7e8938928d802e7582908a5eadaaaf22d64babf1", "http://localhost:8080/auth/callback/github"),
		google.New("44166123467-o6brs9o43tgaek9q12lef07bk48m3jmf.apps.googleusercontent.com", "rpXpakthfjPVoFGvcf9CVCu7", "http://localhost:8080/auth/callback/google"),
		facebook.New("537611606322077", "f9f4d77b3d3f4f5775369f5c9f88f65e", "http://localhost:8080/auth/callback/facebook"),
	)
```

These URLs fix port. But we use the command line parameter to specify it, so it mustn't be fixed.
I think URLs should be as below.

```go:main.go
"http://localhost:" + *host + "/auth/callback/facebook"
```

**Comment by matryer** [comment]
Thanks - you're right. Most of this code is illustrative based on the chapters, and I didn't want to overload people with concepts, but this would be a good way to do this.

**Comment by entyo** [comment]
I see. Think you for your kind.
