### ISSUE TITLE
Address on listen and server method

### ISSUE THREAD

**Issue by ehernandez-xk** [matryer/goblueprints#40]
Hi Mat

Following your book, I have a question related to the function `http.ListenAndSeve()`

If you see in my chat project I build and run the app inside a Docker container
but using my address "localhost:8080" in the function does't work inside the container. (it is not visible out of the container)

```
http.ListenAndServe("localhost:8080", nil)
```

This way works (https://github.com/ehernandez-xk/bp_app/commit/4d5f9c82a4a17fc2facb8e00559fcf39c890e147)
```
http.ListenAndServe(":8080", nil)
```

What does the functions do when ":8080"?

By the way, Your book is awesome!

**Comment by matryer** [comment]
Thank you, I'm glad you're enjoying it. I'd love a [review](https://www.amazon.com/Go-Programming-Blueprints-Mat-Ryer-ebook/dp/B01GQCQ8OW/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1485888808&sr=1-1&keywords=Go+Programming+Blueprints) if you have time.

If you specify `localhost:8080` as the endpoint, it will check to ensure the host is `localhost`. For Docker and other environments (like when it's hosted on another domain) it won't necessarily be bound to the right place.

So `:8080` is like saying: Bind to port :8080 regardless of the incoming host name.

You can also do IP addresses too: `123.234.345.456:8080` and it will only work when hosted at that address.

This is more of a TCP thing than Go.

**Comment by ehernandez-xk** [comment]
Thank you @matryer for the feedback, 

I already did the [review](
https://www.amazon.com/gp/customer-reviews/R1H98JSIKRZHYI/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=B01GQCQ8OW) it was a pleasure.
