### ISSUE TITLE
Chapter 1. Channel description seems to be wrong

### ISSUE THREAD

**Issue by helinwang** [matryer/goblueprints#46]
On page 17.

> You can think of channels as an in-memory thread-safe message queue where senders pass data and receivers read data in a non-blocking, thread-safe way.

I think unbuffered channel (or buffered channel when it's full) is **blocking** - will be blocked until someone reads it.

**Comment by matryer** [comment]
That's true, that sentence could have been better written.

**Comment by helinwang** [comment]
Thanks for confirming! Just want to create this issue for in case other people have the same confusion as I do :)
