### ISSUE TITLE
[Chapter 1] First Chat client typo

### ISSUE THREAD

**Issue by LeamHall** [matryer/goblueprints#47]
Line 18 needs a back tick and comma after the "\</html>".

Addendum: Note that I'm using the electronic version on SafariBooksOnline.

**Comment by LeamHall** [comment]
Page 10 of the second edition print book, which just came in the mail.  :)

**Comment by thalesfsp** [comment]
@matryer Is this repo abandoned?

**Comment by matryer** [comment]
Thanks for reporting it.
