### ISSUE TITLE
[Enhancement] Make changes more visible

### ISSUE THREAD

**Issue by LeamHall** [matryer/goblueprints#48]
In Chapter 1 the files are edited and added to in a non-linear fashion. Recommend makeing changes more visually distinct. For example:

1. Put "add these imports" steps into a separate paragraph or code block.
2. Make bold or use an arrow for changed code in the block.

**Comment by thalesfsp** [comment]
@LeamHall agreed!

**Comment by matryer** [comment]
This is a nice idea, the publisher decides the layout for these kinds of things, but I'll feed this back. Thanks.
