### ISSUE TITLE
[Chapter 1] Print edition odd characters

### ISSUE THREAD

**Issue by LeamHall** [matryer/goblueprints#49]
Page 39, after "The New()", "The Off()", and "The Tracer interface" there's an "a" with a caret on top and two swirly line characters. Think "Twilight Zone". 

Issue is not present in the on-line book; instead it's a dash: "-".

**Comment by matryer** [comment]
Congratulations, you've found the secret char.... no, not really, it's just probably an em dash not included in the character set they used to print it. Please ignore it. Thanks for reporting it.
