### ISSUE TITLE
chapter 5: For nsq on OSX, need to turn on filesharing 

### ISSUE THREAD

**Issue by aastein** [matryer/goblueprints#59]
The steps listed in chapter 5 will result in nsq using a hostname like `Your-MacBook.local`

If the Bonjour service is not enabled, the consumer and nsq_tail will not be able to connect to nsqdlookup

**Fix:**
to fix this, filesharing can be turned on in the OS

**Comment by denis-trofimov** [comment]
I used this way to workaround https://nsq.io/overview/quick_start.html
I have no idea about why all bonjour sharing options on my Mac are off, and I am new to OSX.
I specified IP address for a nsqd:
```sh
nsqd --lookupd-tcp-address=127.0.0.1:4160
```

This was sufficient to make chapter 5 program twittervotes working.
