### ISSUE TITLE
Typo on page 53 of the PDF Version involving redirection through the Location header field.

### ISSUE THREAD

**Issue by lozandier** [matryer/goblueprints#7]
Page 53: `w.Header.SetSet(“Location”, loginUrl)` is accidentally used instead of `w.Header().Set(“Location”, loginUrl)`. 

The former generates an error the compiler immediately recognizes and deviates from what was done earlier (& later) in the book. Accordingly, it seems to me to be a minor typo. 

This typo was found on the latest version of the book that can be found on O'Reilly's e-book service.

**Comment by matryer** [comment]
Thanks for reporting. What chapter is this from?

**Comment by lozandier** [comment]
@matryer Sorry for not explicitly stating the chapter:  This particular error was found in Chapter 2 regarding implementing OAuth.

**Comment by matryer** [comment]
Thanks.

**Comment by matryer** [comment]
Interestingly, this error isn't in print.
