### ISSUE TITLE
Typos/cognitive noise on page 78 of the PDF version involving the naming of variables associated with the Gravatar Avatar Implementation

### ISSUE THREAD

**Issue by lozandier** [matryer/goblueprints#8]
Throughout page 78, there are inconsistencies associated with the naming of instances of and direct references of the `GravatarAvatar` type.

```go
func TestGravatarAvatar(t *testing.T) {
  var gravatarAvitar GravatarAvatar
  client := new(client)
  client.userData = map[string]interface{}{"email":
  "MyEmailAddress@example.com"}
  url, err := gravatarAvitar.GetAvatarURL(client)
  if err != nil {
    t.Error("GravatarAvitar.GetAvatarURL should not return an error")
  }
  if url != "//www.gravatar.com/avatar/0bc83cb571cd1c50ba6f3e8a78ef1346" {
    t.Errorf("GravatarAvitar.GetAvatarURL wrongly returned %s", url)
  }
}
```

The type is  seemingly accidentally referred to as `GravtarAvitar` in error messages compared to earlier and later references to the code snippet on the page. 

Alternatively, and what seems to be more likely) it's unclear if the variable is being intentionally misspelled, but then referred to as `GravtarAvitar` in the formatted error messages. 

If the latter is the case, it's confusing why that is being done, and why the error message doesn't make that clearer by having the first letter of the formatted errors present on the page lowercased. 

## Code Snippet after suggested corrections

```go
func TestGravatarAvatar(t *testing.T) {
  var gravatarAvatar GravatarAvatar
  client := new(client)
  client.userData = map[string]interface{}{"email":
  "MyEmailAddress@example.com"}
  url, err := gravatarAvatar.GetAvatarURL(client)
  if err != nil {
    t.Error("gravatarAvatar.GetAvatarURL should not return an error")
  }
  if url != "//www.gravatar.com/avatar/0bc83cb571cd1c50ba6f3e8a78ef1346" {
    t.Errorf("gravatarAvatar.GetAvatarURL wrongly returned %s", url)
  }
}
```

**Comment by matryer** [comment]
No it’s a typo - and one that is supported by the compiler by the look of it. Thanks for reporting it.
