### ISSUE TITLE
Typo on Page 81: The user's name is hashed instead of their email.

### ISSUE THREAD

**Issue by lozandier** [matryer/goblueprints#9]
On page 81 (*Chapter 3: Three Ways to Implement Profile Pictures*), for some reason, the `userid` has the hash of a user's name (`user.Name()`) instead of their email (`user.Email()`).

This seems unintentional since the hash instructed by readers to user is based on the email (`0bc83cb571cd1c50ba6f3e8a78ef1346`), not the user's name towards coping Gravatar's method of representing emails through its service with an MD5 hash.

**Comment by matryer** [comment]
OK you’re being the technical reviewer on my next book :)

Keep them coming - I’m going to update the main README page with these notes for if people get stuck.

I owe you 1 beer (or beverage of your choice) for each of these.
